= JTS Narayana example

Adapted from
https://github.com/jbosstm/quickstart/tree/master/jts-docker

== How to run

Prepare Podman[https://podman.io] pod for deploy
the Jacorb naming server and JTS transaction service.

[source,sh]
----
podman pod create --name jts -p 127.0.0.1:3528:3528 -p 127.0.0.1:4711:4711
----

Start the naming server and JTS Narayana transaction manager

[source,sh]
----
podman run --pod jts --rm -it  --name jacorb-name-server jboss/jacorb-name-server
podman run -e "JACORB_NAME_SERVER_ENV_NAME_SERVER_PORT=3528"  --pod jts -it --rm --name jts-transaction-service jboss/jts-transaction-service
----




    mvn clean test -Pdocker -DNAME_SERVER_IP=<docker container's IP or Boot2Docker IP> -DNAME_SERVER_PORT=<name server's PORT, defaults to 3528> -DCLIENT_IP=<yoJTSDockerContainerTestur IP accessible for the container>

If you have started containers with Kubernetes:

    mvn clean test -Pdocker -DNAME_SERVER_IP=$(kubectl get pod jts -o=template -t={{.status.podIP}}) -DCLIENT_IP=<your IP accessible for the container>

CLIENT_IP address, is your machines IP address accessible to the docker container. Depending on what connection you are using (ethernet, wlan) you have to pick the appropriate IP.


Mounting local repository as an object store
--------------------------------------------

NOTE: following steps work with manually managed containers.

It is possible to mount one of the local directories to be used as object store. This will allow you to store object store safe in case docker container is removed.

Extra parameter is needed in order to mount the directory. Run transaction service container:

    docker run -p 4711:4711 -it -v /tmp/tx-object-store:/home/tx-object-store --link jacorb-name-server:jacorb-name-server --name jts-transaction-service jboss/jts-transaction-service

Using Postgres as an object store
---------------------------------

NOTE: following steps work with manually managed containers.

Run Postgres container:

    docker run -e POSTGRES_USER=narayana -e POSTGRES_PASSWORD=narayana --name jdbc-object-store postgres

Run transaction service container:

    docker run -p 4711:4711 -it --link jacorb-name-server:jacorb-name-server --link jdbc-object-store:jdbc-object-store -v ${PATH_TO_THE_QUICKSTART}/src/test/resources/docker-narayana-lib:/opt/jboss/lib -v ${PATH_TO_THE_QUICKSTART}/src/test/resources/docker-narayana-config:/opt/jboss/narayana/etc --name jts-transaction-service jboss/jts-transaction-service
